In [2]:
from mxnet import nd

In [3]:
x=nd.arange(12)
x


[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]
<NDArray 12 @cpu(0)>

In [4]:
x.shape

(12,)

In [5]:
x.size

12

In [6]:
x=x.reshape([3, 4])
x


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>

In [7]:
nd.zeros((2,3,4))


[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
<NDArray 2x3x4 @cpu(0)>

In [8]:
nd.ones((3,4))


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [9]:
y=nd.array([[2,1,3,2],[3,4,3,5],[2,5,4,3]])
y


[[ 2.  1.  3.  2.]
 [ 3.  4.  3.  5.]
 [ 2.  5.  4.  3.]]
<NDArray 3x4 @cpu(0)>

In [10]:
nd.random.normal(0,1,shape=(3,4))


[[ 1.16307867  0.48380461  0.29956347  0.15302546]
 [-1.16881478  1.55807114 -0.54594457 -2.35562968]
 [ 0.54144019  2.67850661  1.25463438 -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [11]:
x+y


[[  2.   2.   5.   5.]
 [  7.   9.   9.  12.]
 [ 10.  14.  14.  14.]]
<NDArray 3x4 @cpu(0)>

In [12]:
x*y


[[  0.   1.   6.   6.]
 [ 12.  20.  18.  35.]
 [ 16.  45.  40.  33.]]
<NDArray 3x4 @cpu(0)>

In [13]:
x/y


[[ 0.          1.          0.66666669  1.5       ]
 [ 1.33333337  1.25        2.          1.39999998]
 [ 4.          1.79999995  2.5         3.66666675]]
<NDArray 3x4 @cpu(0)>

In [14]:
y.exp()


[[   7.38905621    2.71828175   20.08553696    7.38905621]
 [  20.08553696   54.59814835   20.08553696  148.41316223]
 [   7.38905621  148.41316223   54.59814835   20.08553696]]
<NDArray 3x4 @cpu(0)>

In [15]:
nd.dot(x,y.T)


[[  13.   25.   22.]
 [  45.   85.   78.]
 [  77.  145.  134.]]
<NDArray 3x3 @cpu(0)>

In [16]:
x,y

(
 [[  0.   1.   2.   3.]
  [  4.   5.   6.   7.]
  [  8.   9.  10.  11.]]
 <NDArray 3x4 @cpu(0)>, 
 [[ 2.  1.  3.  2.]
  [ 3.  4.  3.  5.]
  [ 2.  5.  4.  3.]]
 <NDArray 3x4 @cpu(0)>)

In [17]:
nd.concat(x,y,dim=0)


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [  2.   1.   3.   2.]
 [  3.   4.   3.   5.]
 [  2.   5.   4.   3.]]
<NDArray 6x4 @cpu(0)>

In [18]:
nd.concat(x,y,dim=1)


[[  0.   1.   2.   3.   2.   1.   3.   2.]
 [  4.   5.   6.   7.   3.   4.   3.   5.]
 [  8.   9.  10.  11.   2.   5.   4.   3.]]
<NDArray 3x8 @cpu(0)>

In [19]:
x==y


[[ 0.  1.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

In [20]:
x.sum()


[ 66.]
<NDArray 1 @cpu(0)>

In [21]:
y.sum()


[ 37.]
<NDArray 1 @cpu(0)>

In [22]:
x.norm()


[ 22.49444389]
<NDArray 1 @cpu(0)>

In [23]:
x.norm().asscalar()

22.494444

In [24]:
a=nd.arange(3).reshape((3,1))
b=nd.arange(2).reshape((1,2))
a,b

(
 [[ 0.]
  [ 1.]
  [ 2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[ 0.  1.]]
 <NDArray 1x2 @cpu(0)>)

In [25]:
a+b


[[ 0.  1.]
 [ 1.  2.]
 [ 2.  3.]]
<NDArray 3x2 @cpu(0)>

In [26]:
x


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>

In [27]:
x[1:3]


[[  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
<NDArray 2x4 @cpu(0)>

In [28]:
x[1,2]=9

In [29]:
x


[[  0.   1.   2.   3.]
 [  4.   5.   9.   7.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>

In [30]:
x[1:2,1:3]=12

In [31]:
x


[[  0.   1.   2.   3.]
 [  4.  12.  12.   7.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>

In [32]:
z=y.zeros_like()
before=id(z)
z[:]=x+y
id(z)==before

True

In [33]:
nd.elemwise_add(x,y,out=z)
id(z)==before

True

In [34]:
before=id(x)
x+=y
id(x)==before

True

In [35]:
import numpy as np

p=np.ones((2,3))
d=nd.array(x)
d


[[  2.   2.   5.   5.]
 [  7.  16.  15.  12.]
 [ 10.  14.  14.  14.]]
<NDArray 3x4 @cpu(0)>

In [36]:
d.asnumpy()

array([[  2.,   2.,   5.,   5.],
       [  7.,  16.,  15.,  12.],
       [ 10.,  14.,  14.,  14.]], dtype=float32)

In [37]:
x<y


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

In [38]:
x>y


[[ 0.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [39]:
x


[[  2.   2.   5.   5.]
 [  7.  16.  15.  12.]
 [ 10.  14.  14.  14.]]
<NDArray 3x4 @cpu(0)>

In [40]:
y


[[ 2.  1.  3.  2.]
 [ 3.  4.  3.  5.]
 [ 2.  5.  4.  3.]]
<NDArray 3x4 @cpu(0)>

In [41]:
from mxnet import autograd,nd

In [42]:
x=nd.arange(4).reshape(4,1)
x


[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]]
<NDArray 4x1 @cpu(0)>

In [48]:
x.attach_grad()

In [53]:
with autograd.record():
    y=2*nd.dot(x.T,x)

In [54]:
y.backward()

In [55]:
x.grad,x.grad==4*x

(
 [[  0.]
  [  4.]
  [  8.]
  [ 12.]]
 <NDArray 4x1 @cpu(0)>, 
 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]
 <NDArray 4x1 @cpu(0)>)

In [ ]:
x

In [ ]:
def f(a):
    b=a*2
    while b.norm().asscalar()<1000:
        b=b*2
    if b.sum().asscalar()>0:
        c=b
    else:
        c=100*b
    return c

In [ ]:
a=nd.random.normal(shape=(2,3,2))
a.attach_grad()
with autograd.record():
    c=f(a)
c.backward()

In [ ]:
a.grad==c/a

In [ ]:
print(dir(autograd))

In [ ]:
help(nd.ones_like)